export const defaultColumnVisibility = (auth) =>({
    task: true,
    timer_status: true,
    milestone: auth.getRoleId() !== 5,
    deliverable: true,
    project: true,
    client: true,
    project_manager: true,
    creation_date: true,
    due_date: true,
    start_date: true,
    completion_date: auth.getRoleId() !== 5,
    approved_on: true,
    estimated_time: true,
    hours_logged: true,
    assigned_by: true,
    assigned_to: auth.getRoleId() !== 5,
    status: true,
    progress: auth.getRoleId() !== 5,
    report: true,
})
