// dummy data for project status
export const GoalExtentionHistoryTableData = [
  {
    id: 1,
    goal_start_date: "2022-01-01",
    goal_end_date: "2022-01-31",
    duration: 31,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "In progress",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 4,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 3,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Approved",
  },
  {
    id: 2,
    goal_start_date: "2022-02-01",
    goal_end_date: "2022-02-28",
    duration: 28,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 5,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 2,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Approved",
  },
  {
    id: 3,
    goal_start_date: "2022-03-01",
    goal_end_date: "2022-03-31",
    duration: 31,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "In progress",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 3,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 4,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Pending",
  },
  {
    id: 4,
    goal_start_date: "2022-04-01",
    goal_end_date: "2022-04-30",
    duration: 30,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 4,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 3,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Pending",
  },
  {
    id: 5,
    goal_start_date: "2022-05-01",
    goal_end_date: "2022-05-31",
    duration: 31,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "In progress",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 5,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 2,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Approved",
  },
  {
    id: 6,
    goal_start_date: "2022-06-01",
    goal_end_date: "2022-06-30",
    duration: 30,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 3,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 4,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Approved",
  },
  {
    id: 7,
    goal_start_date: "2022-07-01",
    goal_end_date: "2022-07-31",
    duration: 31,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "In progress",
    reason: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    client_communication_rating: 4,
    negligence_pm: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    negligence_pm_rating: 5,
    pmName: "Belayat Hossain",
    pmId: 2439,
    authorization_status: "Approved",
  },

];

