{
    "id": 2209,
    "name": "Hasan Hafizul Islam",
    "user_name": null,
    "email": "hasan1@seopage1.net",
    "two_factor_secret": null,
    "two_factor_recovery_codes": null,
    "two_factor_confirmed": 0,
    "two_factor_email_confirmed": 0,
    "image": "avatar_blank.png",
    "mobile": "+8801973132603",
    "gender": "male",
    "salutation": null,
    "locale": "en",
    "status": "active",
    "login": "enable",
    "onesignal_player_id": null,
    "last_login": "2024-02-03T18:12:36+06:00",
    "email_notifications": 1,
    "country_id": 18,
    "dark_theme": 0,
    "rtl": 0,
    "two_fa_verify_via": null,
    "two_factor_code": null,
    "two_factor_expires_at": null,
    "admin_approval": 1,
    "permission_sync": 1,
    "google_calendar_status": 1,
    "role_id": 1,
    "shift": null,
    "activation_status": 1,
    "image_url": "http://localhost:8000/user-uploads/avatar/avatar_blank.png",
    "modules": [
        "clients",
        "projects",
        "tickets",
        "invoices",
        "estimates",
        "events",
        "messages",
        "tasks",
        "timelogs",
        "contracts",
        "notices",
        "payments",
        "orders",
        "knowledgebase",
        "employees",
        "attendance",
        "expenses",
        "leaves",
        "leads",
        "holidays",
        "products",
        "reports",
        "settings"
    ],
    "user_other_role": true,
    "role": [
        {
            "user_id": 2209,
            "role_id": 2
        },
        {
            "user_id": 2209,
            "role_id": 1
        }
    ],
    "client_details": null,
    "session": null,
    "employee_detail": {
        "id": 54,
        "user_id": 2209,
        "employee_id": "Seopage1/003",
        "address": null,
        "hourly_rate": null,
        "slack_username": null,
        "department_id": 2,
        "designation_id": 20,
        "joining_date": "2015-03-03T06:00:00+06:00",
        "last_date": null,
        "added_by": 230,
        "last_updated_by": 230,
        "attendance_reminder": null,
        "date_of_birth": null,
        "calendar_view": "task,events,holiday,tickets,leaves",
        "about_me": null,
        "reporting_to": 218,
        "upcoming_birthday": null,
        "designation": {
            "id": 20,
            "name": "Manager",
            "parent_id": 16,
            "added_by": null,
            "last_updated_by": null
        }
    }
}